import axios from "axios";
import { API_BASE } from "@/lib/apiBase";

const pickemBaseUrl = `${API_BASE}/api/pickem`;

export interface PickemQuestionMeta {
  section?: string;
  bracketId?: number | string;
  bracketName?: string;
  stage?: string;
  roundNumber?: number;
  matchNo?: number;
  matchId?: number;
  pickCount?: number;
  statKey?: string;
  [key: string]: unknown;
}

export type PickemOption = string | Record<string, unknown>;

export interface PickemQuestion {
  id: number;
  question: string;
  type: string;
  options: PickemOption[];
  score: number;
  maxChoose: number;
  correctAnswer: PickemOption[];
  meta?: PickemQuestionMeta;
  game_short?: string | null;
  bracket_id?: string | null;
  openTime?: string | null;
  closeTime?: string | null;
}

export interface PickemGenerationSummary {
  total: number;
  singleMatchQuestions: number;
  doubleMatchQuestions: number;
  swissQuestions: number;
  propQuestions: number;
}

export interface PickemQuestionListResponse {
  league_id: string;
  game_short: string;
  type: string;
  count: number;
  questions: PickemQuestion[];
  totalPoint: number;
  totalPointAll: number;
  autoGenerated?: boolean;
  generationSummary?: PickemGenerationSummary | null;
}

export interface SubmitPickemAnswerPayload {
  questionId: number;
  selectedOptions: string[];
  openTime?: string | null;
  closeTime?: string | null;
}

export interface SubmitPickemPredictionPayload {
  userId: string | number;
  user?: Record<string, unknown>;
  answers: SubmitPickemAnswerPayload[];
}

export interface SubmitPickemPredictionResponse {
  success: boolean;
  message: string;
  data?: {
    responseId?: number;
    totalScore?: number;
  };
}

export interface PickemMyAnswerItem {
  questionId: number;
  selectedOptions: string[];
  openTime?: string | null;
  closeTime?: string | null;
  updatedAt?: string;
  question?: string;
  type?: string;
  options?: PickemOption[];
  score?: number;
  maxChoose?: number;
  meta?: PickemQuestionMeta;
  game_short?: string;
  bracket_id?: string | null;
}

export interface PickemMyAnswerResponse {
  league_id: string;
  userId: string;
  user: Record<string, unknown>;
  totalScore: number;
  answers: PickemMyAnswerItem[];
  logs?: unknown[];
}

export interface PickemLeaderboardItem {
  userId: string;
  username: string;
  nickname: string;
  team: string | null;
  logoTeam: string | null;
  img: string | null;
  Score: number;
}

export interface PickemLeaderboardResponse {
  league_id: string;
  leaderboard: PickemLeaderboardItem[];
}

export interface GeneratePickemChallengePayload {
  tournamentId?: number;
  tournament_id?: number;
  gameShort?: string;
  game_short?: string;
}

export interface GeneratePickemChallengeResponse {
  success: boolean;
  message: string;
  league_id: string;
  tournament_id?: number;
  series_id?: number;
  generated?: PickemGenerationSummary;
  updated?: number;
}

export interface UpsertPickemQuestionsPayload {
  id?: number;
  questionId?: number;
  question?: string;
  type?: string;
  options?: Array<string | Record<string, unknown>>;
  score?: number;
  maxChoose?: number;
  correctAnswer?: Array<string | Record<string, unknown>>;
  game_short?: string | null;
  bracket_id?: string | null;
  meta?: Record<string, unknown>;
}

export const getPickemQuestions = ({
  leagueId,
  gameShort = "all",
  type = "all",
}: {
  leagueId: string | number;
  gameShort?: string;
  type?: string;
}) =>
  axios.get<PickemQuestionListResponse>(
    `${pickemBaseUrl}/${gameShort}/${leagueId}/question/${type}`,
  );

export const submitPickemPrediction = (
  leagueId: string | number,
  payload: SubmitPickemPredictionPayload,
) =>
  axios.post<SubmitPickemPredictionResponse>(
    `${pickemBaseUrl}/${leagueId}/submitPrediction`,
    payload,
  );

export const getMyPickemAnswers = (
  leagueId: string | number,
  userId: string | number,
) =>
  axios.get<PickemMyAnswerResponse>(`${pickemBaseUrl}/${leagueId}/myanswer`, {
    params: {
      userId,
      includeLogs: false,
      includeMeta: true,
    },
  });

export const getPickemLeaderboard = (leagueId: string | number) =>
  axios.get<PickemLeaderboardResponse>(
    `${pickemBaseUrl}/pickem/${leagueId}/leaderboard`,
  );

export const generatePickemChallenge = (
  leagueId: string | number,
  payload?: GeneratePickemChallengePayload,
) =>
  axios.post<GeneratePickemChallengeResponse>(
    `${pickemBaseUrl}/${leagueId}/generate`,
    {
      tournamentId: payload?.tournamentId ?? payload?.tournament_id,
      game_short: payload?.game_short ?? payload?.gameShort,
    },
  );

export const generateSeriesPickemChallenge = (
  seriesId: string | number,
  payload?: GeneratePickemChallengePayload & {
    leagueId?: string | number;
    league_id?: string | number;
  },
) =>
  axios.post<GeneratePickemChallengeResponse>(
    `${pickemBaseUrl}/series/${seriesId}/generate`,
    {
      league_id:
        payload?.league_id ?? payload?.leagueId ?? String(seriesId ?? "").trim(),
      game_short: payload?.game_short ?? payload?.gameShort,
    },
  );

export const upsertPickemQuestions = (
  leagueId: string | number,
  payload: UpsertPickemQuestionsPayload[] | UpsertPickemQuestionsPayload,
  apiKey?: string,
) =>
  axios.post(
    `${pickemBaseUrl}/${leagueId}/addquestion`,
    payload,
    apiKey
      ? {
          headers: {
            "x-api-key": apiKey,
          },
        }
      : undefined,
  );
